[package]
name = "terrestrio"
version = "0.1.0"
authors = [
    "William Toll <will@wtoll.com>"
]
edition = "2018"
license = "MPL-2.0 OR GPL-3.0"
resolver = "2"

[dependencies]
winit = "0.25.0"
wgpu = "0.10.1"
tokio = {version = "1.11.0", features = ["rt", "sync", "rt-multi-thread"]}